# Generated by Django 5.2.4 on 2025-07-10 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('image', models.URLField(blank=True)),
                ('species', models.CharField(max_length=80)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6)),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=6)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ADOPTED', 'Adopted'), ('NOT_LISTED', 'Hidden / Internal')], default='AVAILABLE', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'animals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnimalGallery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='animals.animal')),
            ],
            options={
                'db_table': 'animal_gallery',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='AnimalCharacteristic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=80)),
                ('value_bool', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='animals.animal')),
            ],
            options={
                'db_table': 'animal_characteristics',
                'unique_together': {('animal', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AnimalParent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Guardian')], max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentships', to='animals.animal')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offsprings', to='animals.animal')),
            ],
            options={
                'db_table': 'animal_parents',
                'unique_together': {('animal', 'parent', 'relation')},
            },
        ),
    ]
