# Generated by Django 5.2.4 on 2025-07-12 06:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalsBreedGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_weight', models.DecimalField(decimal_places=2, help_text='Average weight range for this group in kg', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Average weight range for this group in kg', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_size_male', models.DecimalField(decimal_places=2, help_text='Minimum size male', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_size_male', models.DecimalField(decimal_places=2, help_text='Maximum size male', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_size_famale', models.DecimalField(decimal_places=2, help_text='Minimum size famale', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_size_famale', models.DecimalField(decimal_places=2, help_text='Maximum size famale', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_breed_groups',
            },
        ),
        migrations.CreateModel(
            name='AnimalsWeightRanges',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=100, unique=True)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('example_breeds', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_weight_ranges',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_breed_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.animalsbreedgroups'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_weight_ranges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.animalsweightranges'),
        ),
    ]
