# Generated by Django 5.2.4 on 2025-07-12 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animalsbreedgroups_animalsweightranges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('characteristic', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'characteristic_keys',
            },
        ),
        migrations.RenameField(
            model_name='animalcharacteristic',
            old_name='value_bool',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='animalcharacteristic',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics_valuess', to='animals.animal'),
        ),
        migrations.AlterUniqueTogether(
            name='animalcharacteristic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='animalcharacteristic',
            name='characteristics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animal_characteristics_values', to='animals.characteristics'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='animalcharacteristic',
            unique_together={('animal', 'characteristics')},
        ),
        migrations.RemoveField(
            model_name='animalcharacteristic',
            name='key',
        ),
    ]
