# Generated by Django 5.2.4 on 2025-07-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcharacteristic',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics_values', to='animals.animal'),
        ),
        migrations.AlterModelTable(
            name='characteristics',
            table='characteristics',
        ),
    ]
