# Generated by Django 5.1.6 on 2025-07-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_city_alter_animal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
