# Generated by Django 5.1.6 on 2025-07-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, help_text='Zalecany rozmiar: 800x600px', null=True, upload_to='animals/images/'),
        ),
        migrations.AlterField(
            model_name='animalparent',
            name='relation',
            field=models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father')], max_length=8),
        ),
    ]
