# Generated by Django 5.1.6 on 2025-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_animal_image_alter_animalparent_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalgallery',
            name='url',
            field=models.ImageField(help_text='Zalecany rozmiar: 800x600px', upload_to='animals/gallery/'),
        ),
    ]
