# Generated by Django 5.1.6 on 2025-07-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_alter_animalgallery_url'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Powiązany post (jeśli istnieje).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='posts.post'),
        ),
    ]
