# Generated by Django 5.1.6 on 2025-07-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_animal_post'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='post',
        ),
        migrations.AddField(
            model_name='animal',
            name='posts',
            field=models.ManyToManyField(blank=True, help_text='Powiązane posty (jeśli istnieją).', related_name='animals', to='posts.post'),
        ),
    ]
