# Generated by Django 5.1.6 on 2025-07-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_remove_animal_post_animal_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='posts',
        ),
    ]
