# Generated by Django 5.1.6 on 2025-07-13 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_remove_animal_posts'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='posts.post'),
        ),
    ]
