# Generated by Django 5.1.6 on 2025-07-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_animal_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalgallery',
            old_name='url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='post',
        ),
    ]
