# Generated by Django 5.2.4 on 2025-07-13 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_rename_url_animalgallery_image_remove_animal_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalsbreedgroups',
            name='max_size_famale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum size famale', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animalsbreedgroups',
            name='max_size_male',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum size male', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animalsbreedgroups',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average weight range for this group in kg', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animalsbreedgroups',
            name='min_size_famale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum size famale', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animalsbreedgroups',
            name='min_size_male',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum size male', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animalsbreedgroups',
            name='min_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average weight range for this group in kg', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
