# Generated by Django 5.2.6 on 2025-09-09 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_alter_animalsbreedgroups_max_size_famale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='characteristics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=20),
        ),
    ]
