# Generated by Django 5.2.6 on 2025-09-09 18:38

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0015_animal_characteristics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='animal',
            name='characteristic_board',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['characteristic_board'], name='animals_charact_6cf98e_gin'),
        ),
    ]
