# Generated by Django 5.2.6 on 2025-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_remove_animal_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='description',
        ),
        migrations.AddField(
            model_name='animal',
            name='descriptions',
            field=models.JSONField(blank=True, help_text='Opis zwierzęcia', null=True),
        ),
    ]
