# Generated by Django 5.2.6 on 2025-09-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0017_remove_animal_description_animal_descriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalgallery',
            options={},
        ),
        migrations.RemoveField(
            model_name='animalgallery',
            name='ordering',
        ),
    ]
