# Generated by Django 5.2.6 on 2025-09-10 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_alter_animalgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalgallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
