# Generated by Django 5.2.6 on 2025-09-10 20:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0019_animalgallery_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalgallery',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='animals/gallery/'), blank=True, null=True, size=5),
        ),
    ]
