# Generated by Django 5.2.6 on 2025-09-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0020_animalgallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalgallery',
            name='images',
        ),
    ]
