# Generated by Django 5.2.6 on 2025-09-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0021_remove_animalgallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.CharField(choices=[('PUPPY_JUNIOR', 'Puppy/Junior'), ('ADULT', 'Adult'), ('SENIOR', 'Senior')], default='PUPPY_JUNIOR', max_length=15),
        ),
    ]
