# Generated by Django 5.2.6 on 2025-09-11 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0022_animal_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='life_period',
            field=models.CharField(choices=[('PUPPY', 'Puppy'), ('ADULT', 'Adult'), ('SENIOR', 'Senior')], default='PUPPY', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(blank=True, help_text='Wiek w latach', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
