# Generated by Django 5.2.6 on 2025-10-31 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0023_animal_life_period_alter_animal_age'),
        ('users', '0009_address_species_delete_speciesorganizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalsbreedgroups',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='breed_groups', to='users.species'),
            preserve_default=False,
        ),
    ]
