# Generated by Django 5.2.9 on 2025-12-23 20:08

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0024_animalsbreedgroups_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[animals.models.Animal.validate_birth_date]),
        ),
    ]
