# Generated by Django 5.2.9 on 2026-01-05 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0026_animal_organization'),
        ('users', '0012_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_org', to='users.organization'),
        ),
    ]
