"""
Django settings for gompet_new project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from corsheaders.defaults import default_headers
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-local-dev-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1").strip().lower() in {"1", "true", "yes", "on"}

DEFAULT_ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "web",
    "nginx",
    "nextjs",
    "nextjs_app",
]
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", ",".join(DEFAULT_ALLOWED_HOSTS)).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.gis',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'users.apps.UsersConfig',
    'animals',
    'litters',
    'common',
    'posts',
    'articles',
    'rest_framework',
    'rest_framework_gis',
    'drf_spectacular',
    'django_filters',
    "django_extensions",
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gompet_new.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



CORS_ALLOW_HEADERS = (
    *default_headers,
    "x-session-token",
    "x-email-verification-key",
    "x-password-reset-key",
)
CORS_ALLOW_CREDENTIALS = True

ASGI_APPLICATION = 'gompet_new.asgi.application'
WSGI_APPLICATION = 'gompet_new.wsgi.application'


CHANNEL_LAYER_BACKEND = os.getenv(
    "CHANNEL_LAYER_BACKEND", "channels_redis.core.RedisChannelLayer"
)
CHANNEL_REDIS_URL = os.getenv("CHANNEL_REDIS_URL")
if CHANNEL_LAYER_BACKEND == "channels.layers.InMemoryChannelLayer":
    channel_layer_config = {}
else:
    redis_host = os.getenv("REDIS_HOST", "redis")
    redis_port = int(os.getenv("REDIS_PORT", "6379"))
    hosts = [CHANNEL_REDIS_URL] if CHANNEL_REDIS_URL else [(redis_host, redis_port)]
    channel_layer_config = {"hosts": hosts}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": CHANNEL_LAYER_BACKEND,
        "CONFIG": channel_layer_config,
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',

        'NAME': os.getenv('POSTGRES_DB', 'gis'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.getenv('POSTGRES_HOST', 'db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pl-PL'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Katalog, do którego collectstatic wrzuci wszystkie pliki
STATIC_ROOT = '/static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "users.User"


REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "common.exceptions.standardized_exception_handler",
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Przykład: globalne klasy uprawnień

    'DEFAULT_PERMISSION_CLASSES': [
        
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Przykład: globalna paginacja (jeśli nie podasz pagination_class na widoku)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # Inne opcje: throttling, parsers, renderers itp.
}


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}



# Email configuration
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "1025"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)

if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@example.com")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

FRONTEND_PASSWORD_RESET_URL = os.getenv(
    "FRONTEND_PASSWORD_RESET_URL", "http://localhost:5001/auth/password-forget/reset/"
)


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
}

# collect tags for v1 and v2
V1_TAGS = [
    {"name": "auth_group", "description": "Operacje związane z uwierzytelnianiem", "x-displayName": "★ Uwierzytelnianie ★"},
    {"name": "auth", "description": "Operacje związane z uwierzytelnianiem", "x-displayName": "Uwierzytelnianie"},
    {"name": "users_group", "description": "Operacje związane z użytkownikami", "x-displayName": "★ Użytkownicy ★"},
    {"name": "users", "description": "Operacje związane z użytkownikami", "x-displayName": "Użytkownicy"},
    {"name": "organizations", "description": "Operacje związane z organizacjami", "x-displayName": "Organizacje"},
    {"name": "organization_members", "description": "Operacje związane z członkami organizacji", "x-displayName": "Członkowie organizacji"},
    {"name": "animals_group", "description": "Operacje związane ze zwierzętami", "x-displayName": "★ Zwierzęta ★"},
    {"name": "animals", "description": "Operacje związane ze zwierzętami", "x-displayName": "Zwierzęta"},
    {"name": "animal_characteristics", "description": "Operacje związane z cechami zwierząt (cechy logiczne)", "x-displayName": "Cechy zwierząt"},
    {"name": "animal_galleries", "description": "Operacje związane z galeriami zwierząt (URL-e obrazów)", "x-displayName": "Galerie zwierząt"},
    {"name": "animal_parentages", "description": "Operacje związane z rodowodami zwierząt (relacje rodzic–dziecko)", "x-displayName": "Rodowody zwierząt"},
    {"name": "animal_family_tree", "description": "Operacje związane z drzewami genealogicznymi zwierząt (przodkowie i potomkowie)", "x-displayName": "Drzewo genealogiczne zwierząt"},
    {"name": "common_group", "description": "Operacje ogólne (komentarze, reakcje)", "x-displayName": "★ Ogólne ★"},
    {"name": "comments", "description": "Operacje związane z komentarzami", "x-displayName": "Komentarze"},
    {"name": "reactions", "description": "Operacje związane z reakcjami", "x-displayName": "Reakcje"},
    {"name": "content_types", "description": "Operacje związane z typami treści", "x-displayName": "Typy treści"},
    {"name": "litters_group", "description": "Operacje związane z miotami", "x-displayName": "★ Mioty ★"},
    {"name": "litters", "description": "Operacje związane z miotami", "x-displayName": "Mioty"},
    {"name": "litter-animals", "description": "Operacje związane ze zwierzętami w miocie", "x-displayName": "Zwierzęta w miocie"},
    {"name": "posts_group", "description": "Operacje związane z postami", "x-displayName": "★ Posty ★"},
    {"name": "posts", "description": "Operacje związane z postami", "x-displayName": "Posty"},
    {"name": "articles_group", "description": "Operacje związane z artykułami", "x-displayName": "★ Artykuły ★"},
    {"name": "articles", "description": "Operacje związane z artykułami", "x-displayName": "Artykuły"},
]

V2_TAGS = [
    {"name": "figma", "description": "Operacje związane z Figma", "x-displayName": "★ --FIGMA-- ★"},
    {"name": "rejestracja_group", "description": "Operacje związane z rejestracją użytkowników", "x-displayName": "★ Rejestracja ★"},
    {"name": "users_figma", "description": "Operacje związane ze zwierzętami", "x-displayName": "Rejestracja"},
    {"name": "logowanie_group", "description": "Operacje związane z logowaniem użytkowników", "x-displayName": "★ Logowanie ★"},
    {"name": "auth", "description": "Operacje związane z logowaniem użytkowników", "x-displayName": "Logowanie"},
    {"name": "strona_glowna_group", "description": "Operacje związane z wyświetlaniem strony głównej", "x-displayName": "★ Strona główna ★"},
    {"name": "animals_new_home", "description": "Operacje związane z wyświetlaniem strony głównej", "x-displayName": "Zwierzęta poszukujace nowego domu"},
    {"name": "organizations_recently_added", "description": "Operacje związane z organizacjami", "x-displayName": "Współpraca z organizacjami"},
    {"name": "articles_latest", "description": "Operacje związane z artykułami", "x-displayName": "Najnowsze publikacje"},
    {"name": "zwierzaki_group", "description": "Operacje związane ze zwierzakami", "x-displayName": "★ Zwierzaki ★"},
    {"name": "animals_filtering", "description": "Operacje związane ze zwierzakami", "x-displayName": "Zwierzak filtrowanie"},
    {"name": "orgaizations_group", "description": "Operacje związane ze zwierzakami", "x-displayName": "★ Schroniska\Hodowle\Fundacje ★"},
    {"name": "organizations_filtering", "description": "Operacje związane z organizacjami", "x-displayName": "Organizacje filtrowanies"},
    {"name": "animal_profile_group", "description": "Operacje związane z członkami organizacji", "x-displayName": "★ Profil zwierzaka Info ★"},
    {"name": "animals", "description": "Operacje związane z profilem zwierzaka", "x-displayName": "Profil zwierzaka (informacje)"},
    {"name": "animal_family_tree", "description": "Operacje związane z cechami zwierząt (cechy logiczne)", "x-displayName": "Family Tree zwierzaka (informacje)"},
    {"name": "comments_organizations", "description": "Operacje związane z filtrowaniem zwierzaków (zaawansowane)", "x-displayName": "Opinie o fundacji (informacje)"},
    {"name": "animals_filtering_advanced", "description": "Operacje związane z cechami zwierząt (cechy logiczne)", "x-displayName": "Inni podopieczni fundacji(informacje)"},
    {"name": "animal_profile_akt_group", "description": "Operacje związane z członkami organizacji", "x-displayName": "★ Profil zwierzaka Akt ★"},
    {"name": "posts_animals", "description": "Operacje związane z profilem zwierzaka", "x-displayName": "Profil zwierzaka (aktywność)"},

    {"name": "profile_orgaanization_group", "description": "Operacje związane z filtrowaniem zwierzaków (zaawansowane)", "x-displayName": "★ Profil schroniska/fundacji/hodoli (informacje)★"},
    {"name": "organizations_profile", "description": "Operacje związane z cechami zwierząt (cechy logiczne)", "x-displayName": "Profil schroniska/fundacji/hodoli (informacje)"},
    {"name": "comments_orgazanizations_profile", "description": "Operacje związane z członkami organizacji", "x-displayName": "Opienie o schronisku/fundacji/hodowli (informacje)"},
    {"name": "organizations_aniamls_filtering", "description": "Operacje związane z profilem zwierzaka", "x-displayName": "Inne zwierzaki tej fundacji (informacje)"},

    {"name": "organizations_akt_group", "description": "Operacje związane z profilem zwierzaka", "x-displayName": "★ Profil schroniska/fundacji/hodoli (aktywnosc)★"},
    {"name": "posts_organizations", "description": "Operacje związane z filtrowaniem zwierzaków (zaawansowane)", "x-displayName": "Profil schroniska/fundacji/hodoli (aktywność)"},

    {"name": "pupils_group", "description": "Operacje związane z cechami zwierząt (cechy logiczne)", "x-displayName": "★ Profil schroniska/fundacji/hodoli (podopeiczni)★"},
    {"name": "organizations", "description": "Operacje związane z członkami organizacji", "x-displayName": "Informacje o organizacji (podopieczni)"},
    {"name": "organizations_profile_pupils", "description": "Operacje związane z członkami organizacji", "x-displayName": "Podopieczni fundacji (podopieczni)"},

    {"name": "miots_group", "description": "Operacje związane z artykułami", "x-displayName": "★ Profil schroniska/fundacji/hodoli (mioty)★"},
    {"name": "organizations_profile_miots", "description": "Operacje związane z członkami organizacji", "x-displayName": "Informacje o organizacji (mioty)"},
    {"name": "organizations_miots", "description": "Operacje związane z miotami", "x-displayName": "Mioty fundacji (mioty)"},

    {"name": "new_profile_group_org", "description": "Operacje związane z miotami", "x-displayName": "★ Nowy profil organizacji ★"},
    {"name": "organizations_new_profile", "description": "Operacje związane z miotami", "x-displayName": "Nowy profil organizacji"},
    {"name": "species", "description": "Operacje związane z miotami", "x-displayName": "Pobierz gatunki dla organizacji"},
    {"name": "animals_breed_groups", "description": "Operacje związane z miotami", "x-displayName": "Pobierz rasy dla organizacji"},
    {"name": "you_in_organization", "description": "Operacje związane z miotami", "x-displayName": "Stanowisko w organizacji"},


    {"name": "new_profile_group_li", "description": "Operacje związane z miotami", "x-displayName": "★ Nowy profil miotu ★"},
    {"name": "litters_new_profile", "description": "Operacje związane z miotami", "x-displayName": "Nowy profil miotu"},
    {"name": "species_miots", "description": "Operacje związane z miotami", "x-displayName": "Gatunki dla miotow"},
    {"name": "animals_breed_groups_miots", "description": "Operacje związane z miotami", "x-displayName": "Rasy dla miotów"},
    


    {"name": "new_profile_group_an", "description": "Operacje związane z miotami", "x-displayName": "★ Nowy profil zwierzaka ★"},
    {"name": "animals_new", "description": "Operacje związane z miotami", "x-displayName": "Dodaj zwierzaka"},
    {"name": "characteristics_animals_values", "description": "Operacje związane z miotami", "x-displayName": "Pobierz cechy zwierzakow"},
    {"name": "animal_galleries", "description": "Operacje związane z miotami", "x-displayName": "Zdjecia zwierzaka"},
    {"name": "animals_characteristics_new", "description": "Operacje związane z miotami", "x-displayName": "Charakterystyka zwierzaka"},



    
    


]
# tags used by the readability-focused v3 schema
V3_TAGS = [
    {"name": "Authentication", "description": "Logowanie, tokeny oraz reset hasla."},
    {"name": "Users", "description": "Konta uzytkownikow i profil."},
    {"name": "Organizations", "description": "Organizacje, role i adresy."},
    {"name": "Animals", "description": "Zwierzeta, cechy, galerie i relacje."},
    {"name": "Litters", "description": "Mioty oraz powiazania ze zwierzetami."},
    {"name": "Posts", "description": "Posty i aktywnosc."},
    {"name": "Articles", "description": "Artykuly i kategorie."},
    {"name": "Community", "description": "Komentarze, reakcje, obserwacje i powiadomienia."},
    {"name": "System", "description": "Pozostale endpointy techniczne."},
]

# common Swagger/OpenAPI options shared by v1, v2 and v3 schema views
SPECTACULAR_SETTINGS_BASE = {
    'COMPONENT_SPLIT_REQUEST': True,
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'SECURITY': [{'BearerAuth': []}],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
    # API routes are mounted from root paths (e.g. /users/, /animals/),
    # so server URL must stay at root for Try it out to call valid endpoints.
    'SERVERS': [
        {
            'url': '/',
            'description': 'Gompet API',
        }
    ],
}

SPECTACULAR_SETTINGS_V1 = {
    **SPECTACULAR_SETTINGS_BASE,
    'TITLE': 'Gompet API v1',
    'DESCRIPTION': 'Dokumentacja API v1',
    'VERSION': '1.0.0',
    'TAGS': V1_TAGS,
}

SPECTACULAR_SETTINGS_V2 = {
    **SPECTACULAR_SETTINGS_BASE,
    'TITLE': 'Gompet API v2',
    'DESCRIPTION': 'Dokumentacja API v2',
    'VERSION': '2.0.0',
    'TAGS': V2_TAGS,
}

SPECTACULAR_SETTINGS_V3 = {
    **SPECTACULAR_SETTINGS_BASE,
    'TITLE': 'Gompet API v3',
    'DESCRIPTION': (
        'Czytelna dokumentacja Swagger. Endpointy sa pogrupowane tematycznie, '
        'opisy sa skrocone, a operacje uporzadkowane alfabetycznie.'
    ),
    'VERSION': '3.0.0',
    'TAGS': V3_TAGS,
    'POSTPROCESSING_HOOKS': [
        'common.openapi.readable_v3_postprocessing_hook',
    ],
    'SORT_OPERATIONS': True,
    'SORT_OPERATION_PARAMETERS': True,
    'SWAGGER_UI_SETTINGS': {
        **SPECTACULAR_SETTINGS_BASE['SWAGGER_UI_SETTINGS'],
        'deepLinking': True,
        'displayRequestDuration': True,
        'docExpansion': 'list',
        'defaultModelsExpandDepth': -1,
        'filter': True,
        'operationsSorter': 'alpha',
        'tagsSorter': 'alpha',
    },
}

# Default schema settings used by management command `manage.py spectacular`.
SPECTACULAR_SETTINGS = {
    **SPECTACULAR_SETTINGS_V3,
    'SERVE_INCLUDE_SCHEMA': False,
    'TITLE': 'Gompet API',
    'DESCRIPTION': 'Domyslna dokumentacja API (v3 - czytelna).',
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5000",  # lub inny adres, z którego odpalasz aplikację Flutter (np. w przeglądarce)
    "http://127.0.0.1:5000",
    "http://localhost:5001",
  
]

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS  # 🔹 Aby uniknąć duplikacji




# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {"console": {"class": "logging.StreamHandler"}},
#     "loggers": {"django": {"handlers": ["console"], "level": "DEBUG"}},
# }
