



volumes:
  postgres_data:
  static_volume:   # <-- tu nic się nie zmienia, ale NAZWA będzie teraz faktycznie użyta

networks:
  webnet:

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - webnet

  web:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /code/django/gompet_new  # <-- ustawiamy working directory na katalog projektu Django
    # ➜ uruchamiamy collectstatic przed Gunicorn-em
    command:
      - sh
      - -c
      - |
        python manage.py collectstatic --noinput &&
          exec uvicorn gompet_new.asgi:application \
            --host 0.0.0.0 \
            --port 8000 \
            --ws websockets \
            --reload
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gis
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"

    volumes:
      - .:/code:rw                         # kod źródłowy
      - ./django/gompet_new/static:/static  # pliki statyczne trafiają tu
      - ./media:/code/django/gompet_new/media  # uploady trafiają do katalogu media
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      retries: 3
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./certs:/etc/nginx/certs:ro
      - ./django/gompet_new/static:/static:ro
      - ./media:/code/django/gompet_new/media:ro  # <-- montujemy katalog media
    networks:
      - webnet

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - webnet
