# Generated by Django 5.2.4 on 2025-07-10 15:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('body', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Opcjonalna ocena 1-5 (np. dla zwierzaków).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_comment_target')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reaction_type', models.CharField(choices=[('LIKE', '👍 Like'), ('LOVE', '❤️ Love'), ('WOW', '😮 Wow'), ('SAD', '😢 Sad'), ('ANGRY', '😡 Angry')], default='LIKE', max_length=10)),
                ('reactable_id', models.PositiveBigIntegerField()),
                ('reactable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reactions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['reactable_type', 'reactable_id'], name='idx_reaction_target')],
                'constraints': [models.UniqueConstraint(fields=('user', 'reaction_type', 'reactable_type', 'reactable_id'), name='uniq_user_reaction_per_object')],
            },
        ),
    ]
