# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_notification_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="organization_member_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
