# Generated by ChatGPT
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_notification_organization_member_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="organization_member_id",
            new_name="created_object_id",
        ),
    ]
