# Generated by Django 5.2.10 on 2026-02-16 11:23

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=common.models.default_follow_notification_preferences),
        ),
    ]
