# Generated by Django 5.2.9 on 2025-12-23 20:08

import json

from django.db import migrations, models


def normalize_article_content(apps, schema_editor):
    Article = apps.get_model("articles", "Article")
    db_alias = schema_editor.connection.alias

    for article in Article.objects.using(db_alias).all().iterator():
        if article.content in (None, ""):
            continue

        if isinstance(article.content, str):
            try:
                json.loads(article.content)
            except json.JSONDecodeError:
                Article.objects.using(db_alias).filter(pk=article.pk).update(
                    content=json.dumps(article.content)
                )
        else:
            Article.objects.using(db_alias).filter(pk=article.pk).update(
                content=json.dumps(article.content)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlecategory_article_categories'),
    ]

    operations = [
        migrations.RunPython(normalize_article_content, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.JSONField(blank=True, help_text='Treść artykułu w formacie JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
