# Generated by Django 5.2.9 on 2025-12-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlecategory_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.JSONField(blank=True, help_text='Treść artykułu w formacie JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
