# Generated by Django 5.2.10 on 2026-05-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_enforce_articlecategory_english_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='group',
            field=models.CharField(choices=[('basics', 'BASICS'), ('by_species', 'BY_SPECIES'), ('daily_care', 'DAILY_CARE'), ('training', 'TRAINING'), ('health', 'HEALTH'), ('shopping', 'SHOPPING'), ('lifestyle', 'LIFESTYLE')], db_index=True, default='basics', max_length=32),
        ),
    ]
