# Generated by Django 5.1.6 on 2025-07-13 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_animal_post'),
        ('posts', '0001_initial'),
        ('users', '0004_address_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['animal'], name='posts_animal__ac9505_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['organization'], name='posts_organiz_2fe5ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('organization__isnull', True)), models.Q(('animal__isnull', True), ('organization__isnull', False)), _connector='OR'), name='exactly_one_parent_fk'),
        ),
    ]
