# Generated by Django 5.2.6 on 2025-09-23 17:31

import json

from django.db import migrations, models


def convert_text_to_json(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    db_alias = schema_editor.connection.alias

    for post in Post.objects.using(db_alias).all():
        value = post.text

        if value in (None, ""):
            continue

        if isinstance(value, str):
            try:
                json.loads(value)
            except json.JSONDecodeError:
                post.text = json.dumps(value)
                post.save(update_fields=["text"])
        else:
            post.text = json.dumps(value)
            post.save(update_fields=["text"])


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
        migrations.RunPython(convert_text_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.JSONField(),
        ),
    ]
