# Generated by Django 5.2.4 on 2025-07-10 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=80)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'litters',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LitterAnimal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_litters', to='animals.animal')),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litter_animals', to='litters.litter')),
            ],
            options={
                'db_table': 'litter_animals',
                'constraints': [models.UniqueConstraint(fields=('litter', 'animal'), name='uniq_litter_animal')],
            },
        ),
    ]
