# Generated by Django 5.1.6 on 2025-07-13 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litters', '0001_initial'),
        ('users', '0004_address_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters', to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='litter',
            index=models.Index(fields=['owner'], name='litters_owner_i_0a9980_idx'),
        ),
        migrations.AddIndex(
            model_name='litter',
            index=models.Index(fields=['organization'], name='litters_organiz_48cc3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='litter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('organization__isnull', True)), models.Q(('owner__isnull', True), ('organization__isnull', False)), _connector='OR'), name='exactly_one_owner_fk'),
        ),
    ]
