# Generated by Django 5.1.6 on 2025-07-13 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_animal_post'),
        ('litters', '0002_litter_organization_and_more'),
        ('users', '0005_alter_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litter',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litters', to='animals.animalsbreedgroups'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litters', to='users.species'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
