# Generated by Django 5.2.6 on 2025-10-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litters', '0003_alter_litter_breed_alter_litter_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litter',
            name='description',
            field=models.JSONField(blank=True, help_text='Opis miotu w formacie JSON', null=True),
        ),
    ]
