# Generated by Django 5.1.6 on 2025-07-12 13:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'breeding_types',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='BreedingTypeOrganizations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('breeding_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='users.breedingtype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_type_organizations', to='users.organization')),
            ],
            options={
                'db_table': 'breeding_type_organizations',
                'unique_together': {('organization', 'breeding_type')},
            },
        ),
        migrations.CreateModel(
            name='SpeciesOrganizations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_organizations', to='users.organization')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='users.species')),
            ],
            options={
                'db_table': 'species_organizations',
                'unique_together': {('organization', 'species')},
            },
        ),
    ]
