# Generated by Django 5.1.6 on 2025-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, upload_to='organizations/images/'),
        ),
    ]
