# Generated by Django 5.2.6 on 2025-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.JSONField(blank=True, help_text='Opis organizacji w formacie JSON.', null=True),
        ),
    ]
