# Generated by Django 5.2.6 on 2025-10-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('SHELTER', 'Schronisko'), ('FUND', 'Fundacja'), ('BREEDER', 'Hodowla'), ('CLINIC', 'Gabinet weterynaryjny'), ('SHOP', 'Sklep zoologiczny'), ('OTHER', 'Inne')], max_length=20),
        ),
    ]
