# Generated by Django 5.2.6 on 2025-10-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='users.species'),
        ),
        migrations.DeleteModel(
            name='SpeciesOrganizations',
        ),
    ]
