# Generated by ChatGPT
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_address_species_delete_speciesorganizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(
                help_text='Opcjonalny właściciel organizacji (użytkownik).',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='organizations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
