# Generated by ChatGPT on 2025-01-30
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_is_deleted_and_alter_organization_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                upload_to="users/images/",
                blank=True,
                null=True,
            ),
        ),
    ]
