# Generated by Django 5.2.9 on 2026-01-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='invitation_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='invitation_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Właściciel / Kierownik'), ('STAFF', 'Pracownik'), ('VOLUNTEER', 'Wolontariusz'), ('MODERATOR', 'Moderator'), ('PARTNER', 'Partner'), ('FINANCE', 'Finanse'), ('CONTENT', 'Twórca treści'), ('VIEWER', 'Obserwator')], default='STAFF', max_length=20),
        ),
    ]
