# Generated by Django 5.2.9 on 2026-01-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_organizationmember_invitation_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("STAFF", "Staff"),
                    ("USER", "User"),
                    ("LIMITED", "Limited"),
                ],
                default="LIMITED",
                max_length=20,
            ),
        ),
    ]
