# Generated by Django 5.2.9 on 2026-03-19 00:00

import re
import unicodedata

from django.db import migrations, models


SPECIES_LABEL_TOKEN_TRANSLATIONS = {
    "pies": "DOG",
    "dog": "DOG",
    "kot": "CAT",
    "cat": "CAT",
    "krolik": "RABBIT",
    "rabbit": "RABBIT",
    "swinka": "GUINEA",
    "morska": "PIG",
    "guinea": "GUINEA",
    "pig": "PIG",
    "chomik": "HAMSTER",
    "hamster": "HAMSTER",
    "szczur": "RAT",
    "rat": "RAT",
    "mysz": "MOUSE",
    "mouse": "MOUSE",
    "ptak": "BIRD",
    "bird": "BIRD",
    "gad": "REPTILE",
    "reptile": "REPTILE",
    "plaz": "AMPHIBIAN",
    "amphibian": "AMPHIBIAN",
    "ryba": "FISH",
    "fish": "FISH",
    "inne": "OTHER",
    "other": "OTHER",
}


def normalize_label(name: str) -> str:
    if not isinstance(name, str):
        return ""

    camel_cased = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    ascii_name = (
        unicodedata.normalize("NFKD", camel_cased)
        .encode("ascii", "ignore")
        .decode("ascii")
    )
    normalized = re.sub(r"[^a-zA-Z0-9]+", "_", ascii_name).strip("_")
    if not normalized:
        return ""

    translated_tokens = [
        SPECIES_LABEL_TOKEN_TRANSLATIONS.get(token.lower(), token.upper())
        for token in normalized.split("_")
        if token
    ]
    return "_".join(translated_tokens)


def backfill_species_label(apps, schema_editor):
    Species = apps.get_model("users", "Species")
    for species in Species.objects.all():
        species.label = normalize_label(species.name)
        species.save(update_fields=["label"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="label",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.RunPython(backfill_species_label, migrations.RunPython.noop),
    ]

